// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace WebReport78.Models;

public partial class DutyShift
{
    public int Id { get; set; }

    public DateOnly Dateduty { get; set; }

    public string Fullname { get; set; }

    public string Rankk { get; set; }

    public string Department { get; set; }

    public string Phonenumber { get; set; }

    public DateOnly MothYearImport { get; set; }

    public DateTime DateCreated { get; set; }

    public DateTime? DateUpdate { get; set; }
}