// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebReport78.Models;

public partial class Identity
{
    public string Guid { get; set; }

    public string Name { get; set; }

    /// <summary>
    /// Card, Fingerprint, FaceID,...
    /// </summary>
    public byte? IdentityVerification { get; set; }

    /// <summary>
    /// Fingerprint: 1-10
    /// </summary>
    public byte? IdentityId { get; set; }

    /// <summary>
    /// normal, hijack, patrol, super, dismiss
    /// </summary>
    public string IdentityType { get; set; }

    public string IdentityTemplate { get; set; }

    public string IdentityData { get; set; }

    public virtual ICollection<StaffIdentity> StaffIdentities { get; set; } = new List<StaffIdentity>();
}