// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace WebReport78.Models;

public partial class Source
{
    public int Id { get; set; }

    public string Guid { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public byte? Type { get; set; }

    public string Description { get; set; }

    public string IdLocation { get; set; }

    public string IdArea { get; set; }

    public string SourceInfo { get; set; }

    public byte? Status { get; set; }

    public long? DateCreated { get; set; }

    public byte? AcCheckType { get; set; }

    public byte? MainStreamTransport { get; set; }

    public byte? SubStreamTransport { get; set; }

    public string UserPermission { get; set; }

    public bool? IsCloudSynced { get; set; }
}