// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace WebReport78.Models;

public partial class Staff
{
    public int Id { get; set; }

    public string GuidStaff { get; set; }

    public int? IdDept { get; set; }

    public int? IdOrg { get; set; }

    public string Code { get; set; }

    public string DocumentNumber { get; set; }

    public string Position { get; set; }

    public string CardIds { get; set; }

    public byte? CardNum { get; set; }

    public byte? FingerprintNum { get; set; }

    public byte? FrNum { get; set; }

    public byte? IrisNum { get; set; }

    public byte? LprNum { get; set; }

    public short? OrderNo { get; set; }

    public bool? IsCloudSynced { get; set; }

    public bool? IsGatewaySynced { get; set; }

    public bool? IsAiBoxesSynced { get; set; }

    public bool? IsAccessDevicesSynced { get; set; }

    public string LocalAvatar { get; set; }

    public string Name { get; set; }

    public byte? Gender { get; set; }

    public DateOnly? Dob { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string Hometown { get; set; }

    public string IdLocation { get; set; }

    public string Description { get; set; }

    public string Avatar { get; set; }

    public string ListImage { get; set; }

    public byte? IdTypePerson { get; set; }

    public long? StartTime { get; set; }

    public long? EndTime { get; set; }

    public byte? Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}