// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebReport78.Models;

public partial class StaffIdentity
{
    public string GuidStaff { get; set; }

    public string GuidIdentity { get; set; }

    public byte? IdentityVerification { get; set; }

    public byte? Status { get; set; }

    public virtual Identity GuidIdentityNavigation { get; set; }

    public virtual Staff GuidStaffNavigation { get; set; }
}