// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace WebReport78.Models;

public partial class Vehicle
{
    public string Lpn { get; set; }

    public string IdLocation { get; set; }

    public string IdStaff { get; set; }

    public byte? ClassifyType { get; set; }

    public string ClassifyProfile { get; set; }

    public string Address { get; set; }

    public string Owner { get; set; }

    public DateTime? RegistrationDate { get; set; }

    public string RegistrationNumber { get; set; }

    public int? SeatCapacity { get; set; }

    public int? LoadingCapacity { get; set; }

    public DateTime? ValidityStartDate { get; set; }

    public DateTime? ValidityEndDate { get; set; }

    public string FullimagePath { get; set; }

    public string PlateimagePath { get; set; }

    public string TicketType { get; set; }

    public decimal? TicketValue { get; set; }

    public bool? IsPriority { get; set; }

    public bool? IsViolation { get; set; }

    public bool? IsDisplay { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedUser { get; set; }

    public string ApprovedUser { get; set; }

    public byte? Status { get; set; }

    public virtual Staff IdStaffNavigation { get; set; }
}